"""initial schema

Revision ID: 5675bef00c60
Revises: 
Create Date: 2026-03-14 12:49:59.599382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5675bef00c60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('folder_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_path')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='runstatus'), nullable=False),
    sa.Column('triggered_by', sa.Enum('manual', 'scheduled', 'system', name='triggeredby'), nullable=False),
    sa.Column('source_type', sa.Enum('slack', 'email', 'calendar', 'github', 'mixed', name='sourcetype'), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('slack', 'email', 'calendar', 'github', 'mixed', name='sourcetype'), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'failed', name='batchstatus'), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'blocked', 'done', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='taskpriority'), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_type', sa.Enum('create_task', 'update_task', 'change_status', 'cancel_task', name='proposaltype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'superseded', name='proposalstatus'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('proposed_title', sa.String(), nullable=True),
    sa.Column('proposed_description', sa.Text(), nullable=True),
    sa.Column('proposed_status', sa.Enum('todo', 'in_progress', 'blocked', 'done', 'cancelled', name='taskstatus'), nullable=True),
    sa.Column('proposed_priority', sa.Enum('low', 'medium', 'high', 'urgent', name='taskpriority'), nullable=True),
    sa.Column('proposed_experience_id', sa.Integer(), nullable=True),
    sa.Column('proposed_due_at', sa.DateTime(), nullable=True),
    sa.Column('proposed_parent_task_id', sa.Integer(), nullable=True),
    sa.Column('proposed_external_ref', sa.String(), nullable=True),
    sa.Column('reason_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Enum('user', 'system', name='proposalreviewedby'), nullable=True),
    sa.Column('created_by', sa.Enum('ai', 'system', name='proposalcreatedby'), nullable=False),
    sa.Column('ingestion_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_batch_id'], ['ingestion_batches.id'], ),
    sa.ForeignKeyConstraint(['proposed_experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['proposed_parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'blocked', 'done', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('changed_by', sa.Enum('user', 'ai', 'system', name='changedby'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_status_history')
    op.drop_table('task_proposals')
    op.drop_table('tasks')
    op.drop_table('ingestion_batches')
    op.drop_table('ingestion_runs')
    op.drop_table('experiences')
    # ### end Alembic commands ###
